spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kkyong?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  h2:
    console:
      enabled: 'true'
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
        show_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: none
  redis:
    host: 127.0.0.1
    port: 6379
  profiles:
    include: oauth